// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';

dotenv.config();

export default {
  datasource: {
    url: process.env.DATABASE_URL,
  },
};
